# Kelompok 2 Kompi 4
## Anggota :
- Achmad Chafid Aufa (SC60401)
- Arif Muhamad Rifai (SC60420)
- Eri Engelina Putri (SC60404)
- Muhammad Yuka Anugrah (SC60423)
- Salamah Zukhrufa Jannah (SC60418)

# Soal 1
----

Kumpulkan data dari seluruh anggota kompi, jika kamu berasal dari kompi A, maka buatlah dataframe df_a, jika kamu berasal dari kompi B, maka buat df_b, dst. Lalu, kumpulkan seluruh data dari seluruh peserta, yang meliputi No. Peserta, Nama, Jurusan, Berat Badan (kg), Tinggi Badan (cm). Dengan dataset yang sudah terkumpul, jawab beberapa pertanyaan berikut

In [ ]:
import pandas as pd

In [ ]:
gsheet = "https://docs.google.com/spreadsheets/d/e/2PACX-1vSakNDrH0vTe-6CC870ofKiNJ_q8_eTR0fTSC7qN0E31CS5ht8M-64VLiPrean0LBgtJeW35_HEbkcW/pub?gid=0&single=true&output=csv"
df_4 = pd.read_csv(gsheet)

In [ ]:
df_4

,No.Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm)
0,SC60401,Chafid,Matematika,76,183
1,SC60402,Elrica,Sistem Informasi,56,157
2,SC60403,Danar,Informatika,64,168
3,SC60404,Eri Engelina,Sistem Informasi,58,155
4,SC60405,Fausi,Fisika,66,170
5,SC60406,Liestha,Pendidikan Bahasa Arab,46,154
6,SC60407,Mirna,Manajemen,45,150
7,SC60408,Myra,Manajemen,65,165
8,SC60409,Lala,Ilmu Komputer,45,150
9,SC60410,Rizal,Ilmu Komputer,67,170
10,SC60411,Syifa,Akuntansi,56,165
11,SC60412,Satria,Informatika,60,170
12,SC60413,Bagas,Agribisnis,47,167
13,SC60414,Fajar,Pend. TIK,63,170
14,SC60415,Uca,Matematika,56,158
15,SC60416,M.Arif,Elektro,51,171
16,SC60417,Fajri,Pend. Bahasa Korea,57,165
17,SC60418,Ama,Meteorologi Terapan,48,150
18,SC60419,Aditya,Statistika,73,173
19,SC60420,Arif,Informatika,75,179
20,SC60421,Diana,Matematika,48,149
21,SC60422,Ingka,Statistika,48,160
22,SC60423,Yuka,Ekonomi Islam,64,170
23,SC60424,Rafa,Statistika,41,160
24,SC60425,Tisya,Statistika,52,160

# 1.  Identifikasi dan jelaskan tipe data apa saja yang ada pada dataframe, ada berapa kolom dan baris, serta informasi apa saja yang terkandung dalam data tersebut?

In [ ]:
df_4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   No.Peserta         25 non-null     object
 1   Nama               25 non-null     object
 2   Jurusan            25 non-null     object
 3   Berat Badan (kg)   25 non-null     int64
 4   Tinggi Badan (cm)  25 non-null     int64
dtypes: int64(2), object(3)
memory usage: 1.1+ KB

•	Tipe data:
  - Kolom No. Peserta, Berat Badan (kg), dan Tinggi Badan (cm) memiliki tipe data integer (int64). Sedangkan Kolom Nama dan Jurusan merupakan tipe data string (object).

•	Jumlah kolom dan baris:
  - Kolom: 5
  - Baris: 25


•	Informasi yang terkandung dalam data:
  - Dalam data tersebut terdapat beberapa informasi seperti Nama, Jurusan, Berat badan, dan Tinggi badan.

# 2. Hitunglah BMI setiap siswa dengan rumus : \begin{align}
        BMI = \frac{(𝐵𝑒𝑟𝑎𝑡 𝑏𝑎𝑑𝑎𝑛 (𝑘𝑔))}{(𝑇𝑖𝑛𝑔𝑔𝑖 𝐵𝑎𝑑𝑎𝑛 (𝑚))^2}
    \end{align}

In [ ]:
berat = df_4['Berat Badan (kg)']
tinggi = df_4['Tinggi Badan (cm)']

In [ ]:
for i in range(len(berat)):
    TB = tinggi[:i+1]/100
    bmi = berat[:i+1] / (TB**2)

In [ ]:
bmi

0     22.694019
1     22.718974
2     22.675737
3     24.141519
4     22.837370
5     19.396188
6     20.000000
7     23.875115
8     20.000000
9     23.183391
10    20.569330
11    20.761246
12    16.852522
13    21.799308
14    22.432303
15    17.441264
16    20.936639
17    21.333333
18    24.391059
19    23.407509
20    21.620648
21    18.750000
22    22.145329
23    16.015625
24    20.312500
dtype: float64

# 3. Buatlah program untuk menghitung BMI!

In [ ]:
berat = float(input('Berat Badan (kg) : '))
tinggi = float(input('Tinggi Badan (cm) : '))

tinggi = tinggi/100
hasil_bmi = berat / (tinggi**2)

print(f'BMI = {hasil_bmi}')

Berat Badan (kg) : 50
Tinggi Badan (cm) : 120
BMI = 34.72222222222222

# 4. Update dataframe df dengan menambahkan hasil perhitungan soal nomor 2, beri nama kolom BMI.

In [ ]:
df_4.insert(loc=5, column='BMI', value=bmi)

In [ ]:
df_4

,No.Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI
0,SC60401,Chafid,Matematika,76,183,22.694019
1,SC60402,Elrica,Sistem Informasi,56,157,22.718974
2,SC60403,Danar,Informatika,64,168,22.675737
3,SC60404,Eri Engelina,Sistem Informasi,58,155,24.141519
4,SC60405,Fausi,Fisika,66,170,22.837370
5,SC60406,Liestha,Pendidikan Bahasa Arab,46,154,19.396188
6,SC60407,Mirna,Manajemen,45,150,20.000000
7,SC60408,Myra,Manajemen,65,165,23.875115
8,SC60409,Lala,Ilmu Komputer,45,150,20.000000
9,SC60410,Rizal,Ilmu Komputer,67,170,23.183391
10,SC60411,Syifa,Akuntansi,56,165,20.569330
11,SC60412,Satria,Informatika,60,170,20.761246
12,SC60413,Bagas,Agribisnis,47,167,16.852522
13,SC60414,Fajar,Pend. TIK,63,170,21.799308
14,SC60415,Uca,Matematika,56,158,22.432303
15,SC60416,M.Arif,Elektro,51,171,17.441264
16,SC60417,Fajri,Pend. Bahasa Korea,57,165,20.936639
17,SC60418,Ama,Meteorologi Terapan,48,150,21.333333
18,SC60419,Aditya,Statistika,73,173,24.391059
19,SC60420,Arif,Informatika,75,179,23.407509
20,SC60421,Diana,Matematika,48,149,21.620648
21,SC60422,Ingka,Statistika,48,160,18.750000
22,SC60423,Yuka,Ekonomi Islam,64,170,22.145329
23,SC60424,Rafa,Statistika,41,160,16.015625
24,SC60425,Tisya,Statistika,52,160,20.312500

# 5. Buatlah status BMI untuk setiap siswa dari kategori berikut, lalu simpan data statusnya dengan nama kolom Status BMI.
- Normal: 18.5-24.9
- Overweight: 25.0-29.9
- Obesity: 30.0-34.9
- Underweight: < 18.5

In [ ]:
status_list = []

for j in bmi:
    if j >= 18.5 and j <= 24.9:
        status_list.append("Normal")
    elif j >= 25.0 and j <= 29.9:
        status_list.append("Overweight")
    elif j >= 30.0 and j <= 34.9:
        status_list.append("Obesity")
    elif j < 18.5:
        status_list.append("Underweight")

In [ ]:
df_4.insert(loc=6, column='Status BMI', value=status_list)

In [ ]:
df_4

,No.Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
0,SC60401,Chafid,Matematika,76,183,22.694019,Normal
1,SC60402,Elrica,Sistem Informasi,56,157,22.718974,Normal
2,SC60403,Danar,Informatika,64,168,22.675737,Normal
3,SC60404,Eri Engelina,Sistem Informasi,58,155,24.141519,Normal
4,SC60405,Fausi,Fisika,66,170,22.837370,Normal
5,SC60406,Liestha,Pendidikan Bahasa Arab,46,154,19.396188,Normal
6,SC60407,Mirna,Manajemen,45,150,20.000000,Normal
7,SC60408,Myra,Manajemen,65,165,23.875115,Normal
8,SC60409,Lala,Ilmu Komputer,45,150,20.000000,Normal
9,SC60410,Rizal,Ilmu Komputer,67,170,23.183391,Normal
10,SC60411,Syifa,Akuntansi,56,165,20.569330,Normal
11,SC60412,Satria,Informatika,60,170,20.761246,Normal
12,SC60413,Bagas,Agribisnis,47,167,16.852522,Underweight
13,SC60414,Fajar,Pend. TIK,63,170,21.799308,Normal
14,SC60415,Uca,Matematika,56,158,22.432303,Normal
15,SC60416,M.Arif,Elektro,51,171,17.441264,Underweight
16,SC60417,Fajri,Pend. Bahasa Korea,57,165,20.936639,Normal
17,SC60418,Ama,Meteorologi Terapan,48,150,21.333333,Normal
18,SC60419,Aditya,Statistika,73,173,24.391059,Normal
19,SC60420,Arif,Informatika,75,179,23.407509,Normal
20,SC60421,Diana,Matematika,48,149,21.620648,Normal
21,SC60422,Ingka,Statistika,48,160,18.750000,Normal
22,SC60423,Yuka,Ekonomi Islam,64,170,22.145329,Normal
23,SC60424,Rafa,Statistika,41,160,16.015625,Underweight
24,SC60425,Tisya,Statistika,52,160,20.312500,Normal

# 6.
## a. Buatlah variabel baru lalu urutkan data berdasarkan tinggi badan dari yang tertinggi ke rendah.
## b. Buat variabel baru lalu urutkan data berdasarkan Nama dari Z – A.

In [ ]:
SBH = df_4.sort_values(by='Tinggi Badan (cm)', ascending=False)

In [ ]:
SBH

,No.Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
0,SC60401,Chafid,Matematika,76,183,22.694019,Normal
19,SC60420,Arif,Informatika,75,179,23.407509,Normal
18,SC60419,Aditya,Statistika,73,173,24.391059,Normal
15,SC60416,M.Arif,Elektro,51,171,17.441264,Underweight
11,SC60412,Satria,Informatika,60,170,20.761246,Normal
22,SC60423,Yuka,Ekonomi Islam,64,170,22.145329,Normal
4,SC60405,Fausi,Fisika,66,170,22.837370,Normal
13,SC60414,Fajar,Pend. TIK,63,170,21.799308,Normal
9,SC60410,Rizal,Ilmu Komputer,67,170,23.183391,Normal
2,SC60403,Danar,Informatika,64,168,22.675737,Normal
12,SC60413,Bagas,Agribisnis,47,167,16.852522,Underweight
10,SC60411,Syifa,Akuntansi,56,165,20.569330,Normal
7,SC60408,Myra,Manajemen,65,165,23.875115,Normal
16,SC60417,Fajri,Pend. Bahasa Korea,57,165,20.936639,Normal
21,SC60422,Ingka,Statistika,48,160,18.750000,Normal
23,SC60424,Rafa,Statistika,41,160,16.015625,Underweight
24,SC60425,Tisya,Statistika,52,160,20.312500,Normal
14,SC60415,Uca,Matematika,56,158,22.432303,Normal
1,SC60402,Elrica,Sistem Informasi,56,157,22.718974,Normal
3,SC60404,Eri Engelina,Sistem Informasi,58,155,24.141519,Normal
5,SC60406,Liestha,Pendidikan Bahasa Arab,46,154,19.396188,Normal
8,SC60409,Lala,Ilmu Komputer,45,150,20.000000,Normal
17,SC60418,Ama,Meteorologi Terapan,48,150,21.333333,Normal
6,SC60407,Mirna,Manajemen,45,150,20.000000,Normal
20,SC60421,Diana,Matematika,48,149,21.620648,Normal

In [ ]:
SBN = df_4.sort_values(by='Nama', ascending=True)

In [ ]:
SBN

,No.Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
18,SC60419,Aditya,Statistika,73,173,24.391059,Normal
17,SC60418,Ama,Meteorologi Terapan,48,150,21.333333,Normal
19,SC60420,Arif,Informatika,75,179,23.407509,Normal
12,SC60413,Bagas,Agribisnis,47,167,16.852522,Underweight
0,SC60401,Chafid,Matematika,76,183,22.694019,Normal
2,SC60403,Danar,Informatika,64,168,22.675737,Normal
20,SC60421,Diana,Matematika,48,149,21.620648,Normal
1,SC60402,Elrica,Sistem Informasi,56,157,22.718974,Normal
3,SC60404,Eri Engelina,Sistem Informasi,58,155,24.141519,Normal
13,SC60414,Fajar,Pend. TIK,63,170,21.799308,Normal
16,SC60417,Fajri,Pend. Bahasa Korea,57,165,20.936639,Normal
4,SC60405,Fausi,Fisika,66,170,22.837370,Normal
21,SC60422,Ingka,Statistika,48,160,18.750000,Normal
8,SC60409,Lala,Ilmu Komputer,45,150,20.000000,Normal
5,SC60406,Liestha,Pendidikan Bahasa Arab,46,154,19.396188,Normal
15,SC60416,M.Arif,Elektro,51,171,17.441264,Underweight
6,SC60407,Mirna,Manajemen,45,150,20.000000,Normal
7,SC60408,Myra,Manajemen,65,165,23.875115,Normal
23,SC60424,Rafa,Statistika,41,160,16.015625,Underweight
9,SC60410,Rizal,Ilmu Komputer,67,170,23.183391,Normal
11,SC60412,Satria,Informatika,60,170,20.761246,Normal
10,SC60411,Syifa,Akuntansi,56,165,20.569330,Normal
24,SC60425,Tisya,Statistika,52,160,20.312500,Normal
14,SC60415,Uca,Matematika,56,158,22.432303,Normal
22,SC60423,Yuka,Ekonomi Islam,64,170,22.145329,Normal

# 7. Filter dataframe df berdasarkan:
- Status BMI di luar Normal.
- Tinggi Badan > 169 cm dan Berat Badan > 60 kg
- Nama yang mengandung huruf “y”.
- Siapa saja yang berat badannya kurang dari 60 kg?

In [ ]:
a = df_4[(df_4['Status BMI'] != "Normal")]

In [ ]:
a

,No.Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
12,SC60413,Bagas,Agribisnis,47,167,16.852522,Underweight
15,SC60416,M.Arif,Elektro,51,171,17.441264,Underweight
23,SC60424,Rafa,Statistika,41,160,16.015625,Underweight

In [ ]:
b = df_4[(df_4['Tinggi Badan (cm)'] > 169) & (df_4['Berat Badan (kg)'] > 60)]

In [ ]:
b

,No.Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
0,SC60401,Chafid,Matematika,76,183,22.694019,Normal
4,SC60405,Fausi,Fisika,66,170,22.837370,Normal
9,SC60410,Rizal,Ilmu Komputer,67,170,23.183391,Normal
13,SC60414,Fajar,Pend. TIK,63,170,21.799308,Normal
18,SC60419,Aditya,Statistika,73,173,24.391059,Normal
19,SC60420,Arif,Informatika,75,179,23.407509,Normal
22,SC60423,Yuka,Ekonomi Islam,64,170,22.145329,Normal

In [ ]:
c = df_4[df_4['Nama'].str.contains('y',case=False)]

In [ ]:
c

,No.Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
7,SC60408,Myra,Manajemen,65,165,23.875115,Normal
10,SC60411,Syifa,Akuntansi,56,165,20.569330,Normal
18,SC60419,Aditya,Statistika,73,173,24.391059,Normal
22,SC60423,Yuka,Ekonomi Islam,64,170,22.145329,Normal
24,SC60425,Tisya,Statistika,52,160,20.312500,Normal

In [ ]:
d = df_4[(df_4['Berat Badan (kg)']<60)]

In [ ]:
d

,No.Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
1,SC60402,Elrica,Sistem Informasi,56,157,22.718974,Normal
3,SC60404,Eri Engelina,Sistem Informasi,58,155,24.141519,Normal
5,SC60406,Liestha,Pendidikan Bahasa Arab,46,154,19.396188,Normal
6,SC60407,Mirna,Manajemen,45,150,20.000000,Normal
8,SC60409,Lala,Ilmu Komputer,45,150,20.000000,Normal
10,SC60411,Syifa,Akuntansi,56,165,20.569330,Normal
12,SC60413,Bagas,Agribisnis,47,167,16.852522,Underweight
14,SC60415,Uca,Matematika,56,158,22.432303,Normal
15,SC60416,M.Arif,Elektro,51,171,17.441264,Underweight
16,SC60417,Fajri,Pend. Bahasa Korea,57,165,20.936639,Normal
17,SC60418,Ama,Meteorologi Terapan,48,150,21.333333,Normal
20,SC60421,Diana,Matematika,48,149,21.620648,Normal
21,SC60422,Ingka,Statistika,48,160,18.750000,Normal
23,SC60424,Rafa,Statistika,41,160,16.015625,Underweight
24,SC60425,Tisya,Statistika,52,160,20.312500,Normal

# 8. Tambahkan nomor urut pada dataframe df sesuai jumlah siswa dan tempatkan kolom nomor baru tersebut di paling ujung kiri sebagai kolom pertama serta beri nama kolomnya “No.”!

In [ ]:
df_4.insert(0, 'No' ,range(1, len(df_4) +1))

In [ ]:
df_4

,No,No.Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
0,1,SC60401,Chafid,Matematika,76,183,22.694019,Normal
1,2,SC60402,Elrica,Sistem Informasi,56,157,22.718974,Normal
2,3,SC60403,Danar,Informatika,64,168,22.675737,Normal
3,4,SC60404,Eri Engelina,Sistem Informasi,58,155,24.141519,Normal
4,5,SC60405,Fausi,Fisika,66,170,22.837370,Normal
5,6,SC60406,Liestha,Pendidikan Bahasa Arab,46,154,19.396188,Normal
6,7,SC60407,Mirna,Manajemen,45,150,20.000000,Normal
7,8,SC60408,Myra,Manajemen,65,165,23.875115,Normal
8,9,SC60409,Lala,Ilmu Komputer,45,150,20.000000,Normal
9,10,SC60410,Rizal,Ilmu Komputer,67,170,23.183391,Normal
10,11,SC60411,Syifa,Akuntansi,56,165,20.569330,Normal
11,12,SC60412,Satria,Informatika,60,170,20.761246,Normal
12,13,SC60413,Bagas,Agribisnis,47,167,16.852522,Underweight
13,14,SC60414,Fajar,Pend. TIK,63,170,21.799308,Normal
14,15,SC60415,Uca,Matematika,56,158,22.432303,Normal
15,16,SC60416,M.Arif,Elektro,51,171,17.441264,Underweight
16,17,SC60417,Fajri,Pend. Bahasa Korea,57,165,20.936639,Normal
17,18,SC60418,Ama,Meteorologi Terapan,48,150,21.333333,Normal
18,19,SC60419,Aditya,Statistika,73,173,24.391059,Normal
19,20,SC60420,Arif,Informatika,75,179,23.407509,Normal
20,21,SC60421,Diana,Matematika,48,149,21.620648,Normal
21,22,SC60422,Ingka,Statistika,48,160,18.750000,Normal
22,23,SC60423,Yuka,Ekonomi Islam,64,170,22.145329,Normal
23,24,SC60424,Rafa,Statistika,41,160,16.015625,Underweight
24,25,SC60425,Tisya,Statistika,52,160,20.312500,Normal

# 9. Cari nilai-nilai berikut:
- Cari nilai terendah dan tertingginya.
- Berapa nilai rata-rata tinggi badan siswa?
- Berapa rata-rata berat badan siswa?
- Ada berapa orang jumlah siswa  yang tercatat pada dataframe df?
- 5 orang dengan nilai BMI tertinggi.
- Ada berapa orang yang tergolong status Underweight, Normal, Overweight, dan Obesity?

In [ ]:
#Mencari Nilai Minimum
BBmin = df_4['Berat Badan (kg)'].min()
print("Nilai minimum Berat Badan:", BBmin)

TBmin = df_4['Tinggi Badan (cm)'].min()
print("Nilai minimum Tinggi Badan:", TBmin)

BMImin = df_4['BMI'].min()
print("Nilai minimum BMI:", BMImin)

#Mencari Nilai Maximum
BBmax = df_4['Berat Badan (kg)'].max()
print("Nilai Maksimum Berat Badan:", BBmax)

TBmax = df_4['Tinggi Badan (cm)'].max()
print("Nilai Makimum Tinggi Badan:", TBmax)

BMImax = df_4['BMI'].max()
print("Nilai Makimum BMI:", BMImax)

Nilai minimum Berat Badan: 41
Nilai minimum Tinggi Badan: 149
Nilai minimum BMI: 16.015624999999996
Nilai Maksimum Berat Badan: 76
Nilai Makimum Tinggi Badan: 183
Nilai Makimum BMI: 24.3910588392529

In [ ]:
#Menghitung Rata-rata
BBmean = df_4['Berat Badan (kg)'].mean()
print("Nilai rata-rata:", BBmean)

TBmean = df_4['Tinggi Badan (cm)'].mean()
print("Nilai rata-rata:", TBmean)

Nilai rata-rata: 57.08
Nilai rata-rata: 163.56

In [ ]:
#Mencari jumlah siswa
jumlah_siswa = len(df_4.axes[0])
print("Jumlah siswa:", jumlah_siswa)

Jumlah siswa: 25

In [ ]:
#Mencari 5 nilai BMI tertinggi
bmi5 = df_4['BMI'].nlargest(n=5)
print("5 Nilai BMI Tertinggi:")
bmi5

5 Nilai BMI Tertinggi:

18    24.391059
3     24.141519
7     23.875115
19    23.407509
9     23.183391
Name: BMI, dtype: float64

In [ ]:
#Mencari jumlah klasterisasi pada status BMI
status_bmi = df_4["Status BMI"].value_counts()
print("Normal =", status_bmi.get("Normal", 0), "Orang")
print("Overweight =", status_bmi.get("Overweight", 0), "Orang")
print("Obesity =", status_bmi.get("Obesity", 0), "Orang")
print("Underweight =", status_bmi.get("Underweight", 0), "Orang")

Normal = 22 Orang
Overweight = 0 Orang
Obesity = 0 Orang
Underweight = 3 Orang

# Soal 2
---

# Program Investasi Jamin-Sugih Co

Perusahaan Investasi Jamin-Sugih Co kami memberikan penawaran investasi terbaik dengan pembagian keuntungan tetap sebesar 25% setiap tahun.

Buatlah program Python yang dapat menerima input dari pengguna dalam bentuk:
Modal Investasi (bilangan bulat antara 0-1.000.000.000)
Jangka Waktu Investasi (bilangan bulat antara 1-25 dalam tahun)
Selain itu, program akan menampilkan error message bahwa modal atau tenure tidak sesuai
ketentuan.

In [ ]:
Modal = float(input("Money Capital : Rp "))
Jangka_waktu = int(input("Investment Tenure (years) : "))

Money Capital : Rp 100000
Investment Tenure (years) : 2

In [ ]:
if (Modal > 0 and Modal <= 1000000000) and (Jangka_waktu >= 1 and Jangka_waktu <= 25):
    modal_awal = Modal
    for i in range(Jangka_waktu):
        modal_awal = modal_awal * 125 / 100
        print("Year {:,.0f},".format(i+1),"your total investment Rp {:,.2f}".format(modal_awal))
    print("Nilai investasi anda setelah", Jangka_waktu, "tahun adalah Rp {:,.2f}".format(modal_awal))
else:
    print("Modal atau jangka waktu tidak sesuai dengan ketentuan")

Year 1, your total investment Rp 125,000.00
Year 2, your total investment Rp 156,250.00
Nilai investasi anda setelah 2 tahun adalah Rp 156,250.00